version: '3'

services:
  web:
    build: .
    command: >
      bash -c "python src/scheduling_system/manage.py makemigrations
      && python src/scheduling_system/manage.py migrate
      && python src/scheduling_system/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
